README.md
Updated README with example of how to get list of instances by appId.
=> Updated README with appId look up example

.eslintrc, .travis.yml, README.md, gulpfile.js, package.json, src/eureka-client.js, test/eureka-client.test.js
Now runs the tests through a pre-process step instead of using babel/register.
Adding ESLint to check code style.
Updating source files to pass lint tests.
Updating travis config to run on more node environments.
Clarity updates to readme.
=> Updating build process.

.eslintrc, README.md, src/default-config.yml, src/eureka-client.js, test/eureka-client.test.js
=> Updating Config

.babelrc, gulpfile.js, package.json, src/Logger.js, src/default-config.js, src/default-config.yml, src/eureka-client.js, test/Logger.test.js
Adding tests for the logger.
Also including new babel config for better code gen.
=> Logger tests

src/eureka-client.js, test/eureka-client.test.js
=> Added coverage and removed if statement in transformRegistry()

src/eureka-client.js, test/eureka-client.test.js
Updated to handle multiple apps and one app. Updated to handle multiple instances and one instance.
=> Instance Caching Inconsistency

README.md, package.json, src/eureka-client.js, test/eureka-client.test.js
- Added deregister call
- Added stop() method to call deregister and stop heartbeats
- Added tests for register and deregister
=> Stop / De-register + tests

.travis.yml, README.md, src/eureka-client.js, test/eureka-client.test.js
This makes the heartbeat code a little cleaner and more testable in the future.
=> Heartbeats

src/default-config.js, src/eureka-client.js
=> Allowing optional disabling of registry polling.

src/EurekaClient.js, test/EurekaClient.test.js
We had a request to configure the instance id based on configuration. Fixes #42.
=> [config] Adding configurable instanceid.

gulpfile.babel.js, test/integration.test.js
This fixes style regressions introduced in #44.
=> Fixing broken styles

src/EurekaClient.js, test/EurekaClient.test.js
Hi!
I think this should fix the tests, could not think of a reason to seperate the two?
Please enlighten me if there is :)
=> Re register on 404

package.json, src/AwsMetadata.js, test/AwsMetadata.test.js
=> Make AwsMetadata filter out null values

package.json, src/EurekaClient.js, test/EurekaClient.test.js
Updating the module to use lodash/merge due to this issue: https://github.com/KyleAMathews/deepmerge/issues/28
=> moved from deepMerge -> lodash/merge

README.md, src/DnsClusterResolver.js, src/EurekaClient.js, src/defaultConfig.js, test/EurekaClient.test.js
Pull Request to add custom requestMiddleware functionality. This will expose the ability to add arbitrary changes to the outgoing request object when making external HTTP calls to eureka.
This will provide the ability for users to easily configure the client for use with various authentication schemes. #82 
Making this PR into the v4 branch because the changes in v4 better facilitate this behavior.
Reviewers: @dflor003, @jquatier, @fmmontas
=> Request middleware

README.md, src/EurekaClient.js, test/EurekaClient.test.js
Add support for `homePageUrl`. Fix issue #88.
=> Add support for homePageUrl

README.md
@jquatier updated readme, let me know if this needs to go in another place or needs to be more descriptive, as i was unsure really where to put this information in Amazon section or 400 section
=> updated readme to reflect aws info for datacenter

.gitignore, package.json, src/EurekaClient.js, test/EurekaClient.test.js
Adds support for comma delimited vips stored in Eureka.
=> Support multiple vips

README.md, src/EurekaClient.js, src/defaultConfig.js, test/EurekaClient.test.js
Fixes #104 by adding a `preferIpAddress` option.
=> adding preferIpAddress option

README.md, src/ConfigClusterResolver.js, src/DnsClusterResolver.js, src/EurekaClient.js, src/defaultConfig.js, test/ConfigClusterResolver.test.js, test/DnsClusterResolver.test.js, test/EurekaClient.test.js
=> Optional registration

.travis.yml, README.md, package.json, src/EurekaClient.js, src/defaultConfig.js, src/deltaUtils.js, test/EurekaClient.test.js, test/deltaUtil.test.js
Introduces experiment mode to fetch delta differences from eureka instead of the full registry. Should have no impact on existing functionality.
=> Delta support
